use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMBottomPlayerServices_Example' do
  pod 'AHFMBottomPlayerServices', :path => '../'

  target 'AHFMBottomPlayerServices_Tests' do
    inherit! :search_paths

    
  end
end
